### ISSUE TITLE
Add support for IE

### ISSUE THREAD

**Issue by mobybit** [mobybit/hugo-natrium-theme#1]
IE doesn't render this theme correctly: the content isn't centered. Suggestions are welcome.

**Comment by pawelgrzybek** [comment]
Hi.

```css
main {
  display: block;
}
```

:)
